apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: docker.io/luccasdsm/guess-game-proxy:latest
        ports:
        - containerPort: 3001
