apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: guess-game
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: luccasdsm/guess-game-proxy:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
