upstream backend {
    server backend-service:5000;
}

server {
    listen 3001;
    
    # API do backend
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Health check
    location /health {
        proxy_pass http://backend/health;
        proxy_set_header Host $host;
    }
    
    # Frontend
    location / {
        proxy_pass http://frontend-service:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}