apiVersion: v1
kind: Secret
metadata:
  name: guess-game-secrets
  namespace: guess-game
type: Opaque
data:
  # Senha do PostgreSQL (base64 encoded)
  # "secretpass" em base64
  POSTGRES_PASSWORD: c2VjcmV0cGFzcw==
