global:
  namespace: guess-game
  imageRegistry: docker.io/luccasdsm

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 15-alpine
  database: postgres
  username: postgres
  password: secretpass

backend:
  enabled: true
  replicaCount: 3
  image:
    repository: guess-game-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5000

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: guess-game-frontend
    tag: latest
    pullPolicy: Always
  service:
    port: 3000
  env:
    REACT_APP_BACKEND_URL: "http://localhost:30300/api"
